version: "3.7"

services:
  mariadb:
    image: mariadb:10.4
    restart: always
    volumes:
      - ./docker/local-storage/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  php:
    build: './docker/php/'
    volumes:
      - ./src/:/var/www/html
    depends_on:
      - mariadb

  nginx:
    image: nginx:1.15
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
