version: '3'

volumes:
    db_data:

services:
    db:
        image: mariadb:10.9
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysite
            MYSQL_USER: mysite
            MYSQL_PASSWORD: password

    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - ./:/app
        working_dir: /app
        depends_on:
            - db

    nginx:
        image: nginx:1.23
        ports:
            - 8080:80
        volumes:
            - ./:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /app
        depends_on:
            - php-fpm
