version: '3.7'

services:
  nginx:
    image: nginx:1.15
    ports:
      - 8080:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    image: php:7.3-fpm
    volumes:
      - ./src:/usr/share/nginx/html
      - ./docker/php/php.ini-development:${PHP_INI_DIR}/php.ini
