version: '3.7'

services:
  php:
    build:
      context: ./docker/php
    ports:
      - 8080:8000
    volumes:
      - ./docker/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./src:/var/www/html
    environment:
      PHP_INI_DIR: /usr/local/etc/php
