version: "3.9"
services:
    postgres:
        image: postgres:15.2-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_USER: ${POSTGRES_USER:-app}
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
